### ISSUE TITLE
Change the name to make purpose more obvious

### ISSUE THREAD

**Issue by tbrowder** [Skarsnik/gptrixie#15]
For whatever reason, I have a hard time finding this module. When I search the [docs](https://modules.raku.org) the name still doesn't click for me until I read the "fine print."

I wish for several things:

1. That it become a "core module" in like manner of **JSON::Fast**.
2. That it be renamed to something like **NativeCall::Helper** or **C::To::Raku** or similar.
3. That the new name be mentioned in the [docs](https://docs.raku.org) along with a short summary and a link to this repo's README.

**Comment by Skarsnik** [comment]
Thanks for using this module. I don't really like having a boring name like NativeCall::RakuFromCHeader.
This can't really be core, since it's poorly written and you need an external software to use it.
I kinda wanted to point to this module in NC documentation, maybe you could propose a PR for this.

**Comment by tbrowder** [comment]
I'll give that a try. Thanks!

**Comment by tbrowder** [comment]
I just pushed Raku/doc PR #3554 and did a ".tell" to you on #raku (assuming you have the same name there which I believe is correct).
